FROM mcr.microsoft.com/windows:2009@sha256:2e42241f1dcbc79d3dc155ad2b06c4c03712495e5bd5b46c674a41c9496292d2

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
